baseURL = 'https://rudiment.gule-gulzar.com'
languageCode = 'en-us'
title = 'Rudiment'
theme = 'hugo-theme-itheme'
enableEmoji=true

defaultContentLanguage = "en" # current only supported 'en' and 'zh-hans', see the 'i18n' folder
[params]
  defaultCover = '/images/default-thumb.jpeg' # default cover image for post not setting cover
  email = 'steady-kitten0n@icloud.com' # the email address display in the footer
  [[params.socialMedia]] # custom social links display in the footer, you can add one or more
    name = 'Github'
    url = 'https://github.com/adorigi'
  [[params.blogroll]] # blogroll links display in the footer, you can add one or more
    name = 'About me'
    url = 'https://gule-gulzar.com'